services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: administrador
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: subasta
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  back:
    image: subasta-back
    environment:
      DB_HOST: database
      DB_PORT: 5433
      DB_USER: administrador
      DB_NAME: subasta
      DB_PASSWORD: admin
    networks:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - fotos-data:/app/uploads/fotos
    depends_on:
      - database

  frontend:
    image: subasta-frontend
    environment:
      API_URL: 'http://back:8080'
    networks:
      - backend
    ports:
      - "80:80"
    depends_on:
      - back

networks:
  backend:
    driver: overlay

volumes:
  db-data:
  fotos-data:
