services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: administrador
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: subasta
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  back:
    image: subasta-back
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: subasta
      DB_USER: administrador
      DB_PASSWORD: admin
    networks:
      - backend
    ports:
      - "8081:8081"
    volumes:
      - fotos-data:/app/uploads/fotos

  frontend:
    image: subasta-frontend
    networks:
      - backend
    ports:
      - "80:80"

networks:
  backend:
    driver: overlay

volumes:
  db-data:
  fotos-data:
